### ISSUE TITLE
Add message view

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/proton-mail#4]

**Comment by Swiip** [comment]
Manager: @matstaz
QA: @DaraQA 
Test server: https://tartiflette.protonmail.blue/login
Test account: `swiip.test`/`swiip.test`

⚠️ Conversations list is totally frozen, it only works with the given test account
As the conversation list is frozen, only prepared mails can be tested. It will be all for this time but will be soon better.

What could be seen:
- Message header: collapsed, extended, show details
- Message body
- Message images: remote and embedded
- Message attachments: footer, download one, download all

**Comment by DeepSpaceHarbor** [comment]
@Swiip  Should this work on mobile devices?
Because right now it's a... bit broken 😅

![image](https://user-images.githubusercontent.com/11393457/69808931-f8a6fe80-11e8-11ea-8502-53576868df26.png)

**Comment by Swiip** [comment]
Didn't think to test it. Obviously, there was no CSS sorcery from @nico3333fr which made it works magically :)

I create an issue to track this need.

**Comment by Swiip** [comment]
Considering the specific nature of the issue, we chose to merge the code after the code review.

All feedbacks from QA will be managed with new issues.
