### ISSUE TITLE
Folder and label colors: from a usability perspective. 

### ISSUE THREAD

**Issue by ObiWanCannobi** [ProtonMail/proton-mail#61]
This will be short and sweet. [The visual language of beta.protonmail.com](https://old.reddit.com/r/ProtonMail/comments/jsdb58/folder_colors/gc17ujr/) is seemingly at odds with usability. Colors allow more options for users to categorize and organize their folders and labels. While the desire to unify the visual design of an application is understandable and necessary, removing an organizational tool on that quest is a detrimental compromise for users who seek to organize and sort their mail. Colors allow a user to make quick visual distinctions between folders and categories should the user choose to sort their mailbox that way. 

I would suggest rather than removing the ability to color a folder/label entirely, the protonmail team implement an option to enable the feature within settings. This will allow the default experience to be more in line with the team's vision, while allowing advanced users to regain functionality they once had. Should the team decide to go this route, I would also ask that a color wheel/hex code selector be added to allow even greater color-based organization. 

I appreciate any time and consideration spent on this topic by the protonmail team.

**Comment by trival** [comment]
just discovered that folder colors are back as opt-in, apparently since Beta 38. Thanks PM.

**Comment by ObiWanCannobi** [comment]
Huh, they actually went and did it.... Cool. This is a massive usability improvement! Thank you PM team.
