### ISSUE TITLE
Moving mail to folder always ends up with consequent "Refresh: 255" response's prop of "GET /api/v4/events/<latest event id value>" request which is a full local cache reset trigger

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-mail#63]
Right after moving the mail to specific folder by calling `PUT /api/mail/v4/messages/label` request the `GET /api/v4/events/<latest event id value>` request occurs with some `EventID: value123` prop in response (treat `value123` as event id value). Then consequent `GET /api/v4/events/value123` always returns the `Refresh: 255` property.

So now any mail move triggers the full data fetch in https://github.com/vladimiry/ElectronMail for those accounts that have the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) flag enabled.

And I guess the https://github.com/ProtonMail/proton-bridge is also affected. If not then maybe you enabled the described behavior for the `x-pm-appversion: WebAccount_<version>`-like header only?

It started to work this way, ie returning `Refresh: 255` prop after mail move, just recently, most likely today (I think not earlier than last week).

CC @bartbutler

**Comment by vladimiry** [comment]
> If not then maybe you enabled the described behavior for the x-pm-appversion: WebAccount_<version>-like header only?

I've tried to put `x-pm-appversion: Bridge_1.5.7` / `x-pm-appversion: LinuxBridge_1.5.7` header for `GET /api/v4/events/<latest event id value>` calll instead of the `x-pm-appversion: WebAccount_<version>` value and it didn't help -  the `Refresh: 255` prop still gets returned soon after the mail move happened.

**Comment by bartbutler** [comment]
Can you try again? We pushed a fix for this.

**Comment by vladimiry** [comment]
Thanks for the hotfix. The issue looks resolved.
