### ISSUE TITLE
Keyboard shortcut A (to archive email) does not work in conversations

### ISSUE THREAD

**Issue by pavog** [ProtonMail/proton-mail#66]
I am using the latest version of the ProtonMail Beta (Protonmail 4.0.0 - Beta 39) and have found a bug with the keyboard shortcuts.

**Steps to reproducs:**
- Log in to protonmail
- Open your inbox
- Open an email conversation (with more than 1 email)
- Press the A key on your keyboard

**Expected behaviour:**
E-mail should be moved to archive + popup message + redirect to inbox.

**Actual behaviour:**
E-mail is not moved, but the popup message appears and no redirect to inbox happens.

**Comment by pavog** [comment]
The problem still exists in Beta 41.

**Comment by aeworxet** [comment]
Works as expected in
**Release: 4.0.2 — July 14, 2021**
both in 'Column' and 'Row' views.

**Comment by pavog** [comment]
Thank you for the reminder. Yes, it works in the newest version 👍
