### ISSUE TITLE
Publish actual code

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-mail#75]
https://mail.protonmail.com/assets/version.json 4.1.49 vs published code 4.1.45
https://account.protonmail.com/assets/version.json 4.2.17 vs published code 4.2.9
https://drive.protonmail.com/assets/version.json 4.1.24 vs published code 4.1.23
https://calendar.protonmail.com/assets/version.json 4.1.19-prod.1 vs published code 4.1.18 

Asking since I created similar issues many times before (CC @bartbutler):
- Can't the code publishing be automated (be part of the deploying continuous integration job)?
- Or can't you publish the code to GitHub first and then build/deploy from the GitHub?

**Comment by mmso** [comment]
We are soon going to be moving these repositories to a monorepo and will update the open source publishing process with it

**Comment by vladimiry** [comment]
Great, thanks.

**Comment by vladimiry** [comment]
According to https://account.protonmail.com/assets/version.json the `account` project's code has not been published.
