### ISSUE TITLE
app.protonmail.ch

### ISSUE THREAD

**Issue by Ammako** [ProtonMail/proton-mail#76]
Hiya. Will the .ch domain be upgraded to v4 at some point? Just nudging, in case it might have simply been forgotten. I don't mind waiting, just wanted to make sure.

**Comment by bartbutler** [comment]
Once we have v4 on our Tor site the plan is to discontinue app.protonmail.ch and redirect to mail.protonmail.com, as app.protonmail.ch provides a negligible security benefit and anyone with concerns about using the .com site is welcome to use Tor as a substitute.

**Comment by Ammako** [comment]
That's probably good enough, can still use that address as bookmark and if anything ever happens to your .com domain, you can just turn off the redirect on your end and move the site to .ch and the user basically won't even notice the change.

**Comment by bartbutler** [comment]
I suggest you update your bookmark to mail.protonmail.com because even were the scenario you describe to happen, the url would no longer be app.protonmail.ch.
