### ISSUE TITLE
Publish actual code

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-mail#77]
Placing new issue since could not reopen the #75.

The code of the following projects have not been published:
https://mail.protonmail.com/assets/version.json (hash b0ae512, the commit doesn't belong to any branch)
https://account.protonmail.com/assets/version.json (hash 8997023)

**Comment by dhoko** [comment]
:wave: 

Indeed it's because there was a release branch for this project. I pushed it here https://github.com/ProtonMail/proton-mail/tree/release/4.0.1

**Comment by vladimiry** [comment]
Thanks.
