### ISSUE TITLE
New advanced search form

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/proton-mail#9]
Advanced search (only applicable to mail right now)
- [ ] the user should be able to see a drop down caret if the Advanced search function is present
- [ ] the user should be able to hover over the caret and see it highlighted
- [ ] the user should be able to click on the caret to open the advanced search options, and the caret will flip 180°
- [ ] the user should be able to make selection in the advanced search pop over and see his selection fit inside the search bar in front of the search string
- [ ] if there are more search options than can be displayed in the search bar, then the user will be able to navigate between them with left / right arrows
- [ ] advanced search drop down is re-used for the responsive view.

Features constraint:
- only 1 location can be selected from the dropdown
- only 1 address can be selected from the dropdown
- From can have as many email addresses as possible seperated by colons
- to can have as many email addresses as possible seperated by colons
- Date range must have first date being anterior to second date
- User should not be able to select a date in the future

Note:
- content search is not yet available. Shown for reference only.

Zeplin link:
- https://app.zeplin.io/project/5d5b7ea26986389b1e7b265c/screen/5e0a04ff9c2f1097b82fb3d3

**Comment by matstaz** [comment]
Specs need to be reviewed with @EpokK and @jovanjovanovski
